using System;

namespace WizLib.Application.Seed
{
    public class AuthorInitializer
    {
        private static readonly string[] Forenames =
        {

            "Aldo",
            "Aleyn",
            "Alford",
            "Amherst",
            "Angel",
            "Anson",
            "Archibald",
            "Aries",
            "Arwen",
            "Astin",
            "Atley",
            "Atwell",
            "Audie",
            "Avery",
            "Ayers",
            "Baker",
            "Balder",
            "Ballentine",
            "Bardalph",
            "Barker",
            "Barric",
            "Bayard",
            "Bishop",
            "Blaan",
            "Blackburn",
            "Blade",
            "Blaine",
            "Blaze",
            "Bramwell",
            "Brant",
            "Brawley",
            "Breri",
            "Briar",
            "Brighton",
            "Broderick",
            "Bronson",
            "Bryce",
            "Burdette",
            "Burle",
            "Byrd",
            "Byron",
            "Cabal",
            "Cage",
            "Cahir",
            "Cavalon",
            "Cedar",
            "Chatillon",
            "Churchill",
            "Clachas",
            "Addison",
            "Alivia",
            "Allaya",
            "Amarie",
            "Amaris",
            "Annabeth",
            "Annalynn",
            "Araminta",
            "Ardys",
            "Ashland",
            "Avery",
            "Bedegrayne",
            "Bernadette",
            "Billie",
            "Birdee",
            "Bliss",
            "Brice",
            "Brittany",
            "Bryony",
            "Cameo",
            "Carol",
            "Chalee",
            "Christy",
            "Corky",
            "Cotovatre",
            "Courage",
            "Daelen",
            "Dana",
            "Darnell",
            "Dawn",
            "Delsie",
            "Denita",
            "Devon",
            "Devona",
            "Diamond",
            "Divinity",
            "Duff",
            "Dustin",
            "Dusty",
            "Ellen",
            "Eppie",
            "Evelyn",
            "Everilda",
            "Falynn",
            "Fanny",
            "Faren",
            "Freedom",
            "Gala",
            "Galen",
            "Pagination"
        };

        private static readonly string[] Surnames =
        {
            "Aaberg",
            "Aaby",
            "Aadland",
            "Aagaard",
            "Aagard",
            "Aaker",
            "Aakre",
            "Aalbers",
            "Aalto",
            "Aamodt",
            "Aamot",
            "Aanenson",
            "Aardema",
            "Aarhus",
            "Aaron",
            "Aarons",
            "Aaronson",
            "Aas",
            "Aase",
            "Aasen",
            "Abad",
            "Abadi",
            "Abadie",
            "Abair",
            "Abajian",
            "Abalos",
            "Abar",
            "Abarca",
            "Abare",
            "Abascal",
            "Abate",
            "Abato",
            "Abbas",
            "Abbasi",
            "Abbate",
            "Abbatiello",
            "Abbe",
            "Abbett",
            "Abbey",
            "Abbitt",
            "Abbot",
            "Abbott",
            "Abboud",
            "Abbruzzese",
            "Abbs",
            "Abbuhl",
            "Abby",
            "Abdalla",
            "Abdallah",
            "Abdella",
            "Abdelnour",
            "Abdelrahman",
            "Abdi",
            "Abdo",
            "Abdon",
            "Abdoo",
            "Abdul",
            "Abdulla",
            "Abdullah",
            "Abe",
            "Abebe",
            "Abed",
            "Abee",
            "Abegg",
            "Abegglen",
            "Abeita",
            "Abel",
            "Abela",
            "Abele",
            "Abeles",
            "Abell",
            "Abella",
            "Abello",
            "Abelman",
            "Abeln",
            "Abels",
            "Abelson",
            "Abend",
            "Abendroth",
            "Aber",
            "Abercrombie",
            "Aberg",
            "Aberle",
            "Aberman",
            "Abernathey",
            "Abernathy",
            "Abernethy",
            "Abert",
            "Abeyta",
            "Abid",
            "Abila",
            "Abitz",
            "Abke",
            "Able",
            "Ableman",
            "Abler",
            "Ables",
            "Abner",
            "Abney",
            "Pagination"
        };

        private static readonly int ForenameLength = Forenames.Length;
        private static readonly int SurnameLength = Surnames.Length;

        public static string Fullname()
        {
            var random = new Random();

            return $"{Forenames[random.Next(ForenameLength)]} {Surnames[random.Next(SurnameLength)]}";
        }

        public static string Forename()
        {
            var random = new Random();

            return Forenames[random.Next(ForenameLength)];
        }

        public static string Surname()
        {
            var random = new Random();

            return Surnames[random.Next(ForenameLength)];
        }
    }
}